server:
  port: 8090
  context-path: /

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3308/watcha
    username: root
    password: koreait

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

